#!/bin/bash
# merges the geoknow scheme with the instance data
grep -v "@prefix" workpackages.ttl > /tmp/workpackages_np.ttl
grep -v "@prefix" tasks.ttl > /tmp/tasks_np.ttl
grep -v "@prefix" deliverables.ttl > /tmp/deliverables_np.ttl
cat geoknow_schema.ttl /tmp/workpackages_np.ttl /tmp/tasks_np.ttl /tmp/deliverables_np.ttl > geoknow_merged.ttl
