<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org header template
 */
?>
<header id="header">
    <h1><a href="/"><img src="<?php echo $this->baseUri; ?>/images/geoknow-logo.png" alt="GeoKnow" style="height: 121px; width: 552px;"/></a></h1>
<?php
$navOptions = array(
    'navResource' => 'http://geoknow.eu/Navigation/Main',
    'navId' => 'nav-main',
    'suffix'    => '<!-- /#nav-main -->',
    'activeUrl' => $this->resourceUri
);
echo $this->navigationList($navOptions);
?>
<?php
$navOptions = array(
    'navResource' => 'http://geoknow.eu/Navigation/Top',
    'navId' => 'nav-top',
    'suffix'    => '<!-- /#nav-top -->',
    'activeUrl' => $this->resourceUri
);
echo $this->navigationList($navOptions);
?>
</header> <!-- /#header -->
<hr class="hideme" />

