<?php
/**
* This file is part of the {@link http://ontowiki.net OntoWiki} project.
*
* @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
* @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
*/

/**
* aksw.org layout template
*
* the most out template layer
*/

// edit link for the universal edit button
$editUrl = $this->wikiBaseUrl .'view?r=' . urlencode($this->resourceUri);

// this is the standard template data
$templateData = $this->templateData;
?><!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/"
 <?php foreach ($this->namespaces as $prefix => $ns): ?><?php echo ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?> >
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <meta name="generator" content="<?php echo $this->generator ?>" />
    <link rel="alternate" type="application/rdf+xml" href="<?php echo $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?php echo $this->pingbackUrl ?>" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script type="text/javascript">document.documentElement.className += 'js';</script>

    <link
        rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>"
        href="<?php echo $this->resourceUri?>" />

    <link
        rel="stylesheet" type="text/css" media="all"
        href="<?php echo $this->baseUri ?>/css/all.dev.css"
        title="Standard" />
    <link
        rel="icon"
        type="image/png"
        href="<?php echo $this->baseUri ?>/images/favicon.png" />

    <link rel="alternate"
        type="application/wiki"
        title="Edit this page!"
        href="javascript:RDFauthor.myEdit()" />

    <!-- TODO: we should include all the js via a parallel loading script.
* separates the js logic from templates/html/caches
* improves performance
-->
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery-ui.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUri ?>/libs/rscarousel/jquery.rs.carousel.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUri ?>/libs/rscarousel/jquery.rs.carousel-autoscroll.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUri ?>/libs/fancybox/jquery.fancybox-1.3.4.css"/>
    <script type="text/javascript" src="<?php echo $this->baseUri ?>/libs/fancybox/jquery.fancybox-1.3.4.pack.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUri ?>/scripts/settings/media.dev.js"></script>
	
	<!-- Scripts for sharethis widget -->
	<script type="text/javascript">var switchTo5x=true;</script>
	<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
	<script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>

    <title><?php echo $templateData['title'] ?> &mdash; <?php echo $this->siteConfig['name'] ?></title>

<!-- google analytics -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38075857-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
    <script src="http://static.simile.mit.edu/exhibit/api-2.0/exhibit-api.js" type="text/javascript"></script>
    <script>SimileAjax.History.enabled = false;</script>
    <link href="http://docs.aksw.org/BibsonomyProxy/exhibit-proxy.php?suffix=user/aksw/group_aksw&callback=cb" type="application/jsonp" rel="exhibit/data" ex:jsonp-callback="cb" />
</head>
<body>
    <div class="page_margins">
        <div id="page">
                <?php echo $this->partial('local/header.phtml', $templateData) ?>
            <article id="content">
                <?php echo $this->renderx(); ?>
            </article> <!-- /#content -->
            <section id="sidecontent">
                <div id="associations">
                    <h2>Hosted by</h2>
                    <a href="http://www.uni-leipzig.de"><img src="<?php echo $this->baseUri; ?>/images/logo-unileipzig.png" alt="Universität Leipzig" /></a> <span>,</span>
                    <a href="http://infai.org"><img src="<?php echo $this->baseUri; ?>/images/logo-infai.png" alt="InfAI: Institut für Angewandte Informatik" /></a>
					<h2>Funded by</h2>
					<div>
						<a href="http://cordis.europa.eu/fp7/home_en.html">
						<img alt="EU Seventh Framework Programme (FP7)" src="http://www.geoknow.eu/site/images/eu-logos.jpg">
						</a>
					</div>
                </div> <!-- /#associations -->
                <?php echo $this->partial('local/feed.phtml', $templateData) ?>
            </section> <!-- /#sidecontent -->
            <?php echo $this->partial('local/footer.phtml', $templateData) ?>
        </div> <!-- /#page -->
    </div> <!-- /.page_margins -->
	<!-- Sharethis widget -->
	<div>
		<script type="text/javascript">stLight.options({publisher: "45690818-21c8-414f-abaa-5a471a44e7ea"});</script>
		<script>
		var options={ "publisher": "45690818-21c8-414f-abaa-5a471a44e7ea", "position": "left", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["googleplus", "twitter", "linkedin", "facebook", "email"]}};
		var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
		</script>
	</div>
</body>
</html>
