<?php
/*
 * This template does not output anything but a specific partial output
 */

// this is the standard template data
$templateData = array(
                'title' => $this->title,
                'resourceUri' => $this->resourceUri,
                'description' => $this->description,
                'descriptionHelper' => $this->descriptionHelper,
                'options'           => $this->options
        );

if (isset($this->description['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'])) {
    $types = array ();
    foreach ($this->description['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'] as $property) {
        if ((isset($property['value'])) && (Erfurt_Uri::check($property['value']))) {
            $types[$property['value']] = true;	    
        }
echo "types: ";
echo $types;
    }
echo "switching now:";
    switch ($types) {
        case (isset($types['http://purl.org/research-fp#WorkPackage'])):
            echo "debug: this is a workpackage! ";
            echo $this->partial($this->siteId . '/types/workpackage.phtml', $templateData);
            break;
        case (isset($types['http://purl.org/research-fp#Task'])):
            echo $this->partial($this->siteId . '/types/task.phtml', $templateData);
            break;
        case (isset($types['http://purl.org/research-fp#Deliverable'])):
            echo $this->partial($this->siteId . '/types/deliverable.phtml', $templateData);
            break;
        case (isset($types['http://rdfs.org/sioc/types#WikiArticle'])):
        case (isset($types['http://rdfs.org/sioc/ns#Post'])):
            echo $this->partial($this->siteId . '/types/article.phtml', $templateData);
            break;
        case (isset($types['http://usefulinc.com/ns/doap#Project'])):
            echo $this->partial($this->siteId . '/types/project.phtml', $templateData);
            break;
        case (isset($types['http://lod2.eu/schema/Partner'])):
        case (isset($types['http://xmlns.com/foaf/0.1/Organization'])):
            echo $this->partial($this->siteId . '/types/partner.phtml', $templateData);
            break;
        case (isset($types['http://xmlns.com/foaf/0.1/Person'])):
            echo $this->partial($this->siteId . '/types/person.phtml', $templateData);
            break;
        default:
	    echo "debug: no template found :-(";
            // no specific template found
            echo $this->partial($this->siteId . '/default.phtml', $templateData);
            break;
    }
} 
?>
