<?php
$hookline = $this->literal(array(
    'property' => 'rdfs:label',
    'class' => 'hookline',
    'prefix' => '<span class="hideme">:</span> '
));
$deliverableIdentifier = $this->literal(array(
    'property' => 'fp:deliverableIdentifier'));

$abstract = $this->literal(array(
    'property' => 'dcterms:description',
    'tag' => 'p',
    'class' => 'abstract'
));

?>
<header class="intro">
    <h1><?php echo $deliverableIdentifier. " &ndash; " . $this->title; /*. $hookline*/ ?></h1>
</header> <!-- /.intro -->
<?php
echo $abstract;
//echo $this->literal(array('tag' => 'div', 'class' => 'abstract')); // uses default content properties
#echo $this->renderx(array('template' => 'local/items/publications.phtml'));

