<?php
$title       = $this->title;
$resourceUri = $this->resourceUri;
$heading     = '';

$description = $this->literal(array(
    'property' => 'dcterms:description',
    'tag' => 'div',
    'class' => 'description'
));

$homepage = $this->literal(array('property' => 'foaf:homepage', 'plain' => 'true'));

// prepare the heading
if ($homepage != '') {
    $heading = $this->link(array(
        'uri'    => $homepage, 'text' => $title,
        'direct' => true,
        'prefix' => '<header class="intro"><h1>', 'suffix' => '<h1/></header>'
    ));
} else {
    $heading = '<header class="intro"><h1>'. $title .'</h1></header>' .PHP_EOL;
}

// prepare the logo
$logo = '';
$logoimg       = $this->img(array(
    'property' => 'foaf:logo',
    'class'    => 'logo',
    'alt'      => 'logo ' . $title,
    'prefix'   => '<div class="logo">',
    'suffix'   => '</div>'
));

if ($logoimg != '') {
    if ($homepage != '') {
        $logo = $this->link(array(
            'uri'  => $homepage,
            'direct' => true,
            'text' => $logoimg
        ));
    } else {
       $logo = $logoimg;
    }
} else {
    $logo = '';
}

?>

<div class="nav-sidelinks"> 
  <ul><li>Partners</li>
    <li> 
      <?php 
      echo $this->query(array(
        'where' => '?resourceUri a fp:Partner. ',
        'template' =>'lmenu' 
        ))
      ?>
    </li>
  </ul>
</div>

<div about="<?php echo $this->curie($resourceUri) ?>"
    class="abstract <?php echo $logo?'abstract-with-logo':''; ?>" >
    <?php echo $heading, $logo, $description ?>
    <?php

    // LEADING WP
    echo $this->query(array(
        'where' => '?resourceUri fp:leadPartner <'.$resourceUri.'>. ?resourceUri a fp:WorkPackage. ?resourceUri fp:workpackageNumber ?wpnumber.',
	'orderby'=> 'ASC(?wpnumber)',
        'template' => 'identifiertable',
        'prefix' => '<h2>Leading workpackages:</h2>'
    ));

    // TASKS 
    echo $this->query(array(
        'where' => '?resourceUri fp:partner <'.$resourceUri.'>. ?resourceUri a fp:Task. ?resourceUri dcterms:identifier ?id.',
        'orderby'=> 'ASC(?id)',
        'template' => 'identifiertable',
        'prefix' => '<h2>Contributing to tasks:</h2>'
    ));
     ?>
</div>
 
