<?php
$hookline = $this->literal(array(
    'property' => 'rdfs:label',
    'class' => 'hookline',
    'prefix' => '<span class="hideme">:</span> '
));
$identifier = $this->literal(array(
    'property' => 'http://purl.org/dc/terms/identifier'));

$description = $this->literal(array(
    'property' => 'http://purl.org/dc/terms/description',
    'tag' => 'p',
    'class' => 'abstract'
));

?>
<header class="intro">
    <h1><?php echo $identifier. " &ndash; " . $this->title; /*. $hookline*/ ?></h1>
</header> <!-- /.intro -->

<?php
echo $description;
echo $this->query(array(
        'where' => '?resourceUri fp:task <'.$this->resourceUri.'>. ?resourceUri a fp:Deliverable. ?resourceUri fp:deliverableNumber ?deliverableNumber.',
	'orderby' => 'ASC(?deliverableNumber)', 
        'template' => 'identifiertableDocument',
        'prefix' => '<h2>Deliverables</h2>'
    ));

echo $this->query(array(
        'where' => '<'.$this->resourceUri.'>  fp:workpackage ?wp . ?resourceUri fp:workpackage ?wp . ?resourceUri fp:taskNumber ?taskNumber . FILTER(<'.$this->resourceUri.'> != ?resourceUri)',
	'orderby' => 'ASC(?taskNumber)', 
        'template' => 'identifiertable',
        'prefix' => '<h2>Other Tasks in this Workpackage</h2>'
    ));

//echo $this->literal(array('tag' => 'div', 'class' => 'abstract')); // uses default content properties
#echo $this->renderx(array('template' => 'local/items/publications.phtml'));

