<?php
$hookline = $this->literal(array(
    'property' => 'rdfs:label',
    'class' => 'hookline',
    'prefix' => '<span class="hideme">:</span> '
));
$identifier = $this->literal(array(
    'property' => 'gk:identifier'));

$description = $this->literal(array(
    'property' => 'dcterms:description',
    'tag' => 'p',
    'class' => 'abstract'
));

?>
<header class="intro">
    <h1><?php echo $identifier. " &ndash; " . $this->title; /*. $hookline*/ ?></h1>
</header> <!-- /.intro -->
<?php
echo $description;

 echo $this->query(array(
        'where' => '?resourceUri fp:task <'.$this->resourceUri.'>. ?resourceUri a fp:Deliverable.',
        'template' => 'identifiertable',
        'prefix' => '<h1>Tasks</h1>'
    ));

//echo $this->literal(array('tag' => 'div', 'class' => 'abstract')); // uses default content properties
#echo $this->renderx(array('template' => 'local/items/publications.phtml'));

