<?php
$hookline = $this->literal(array(
    'property' => 'rdfs:label',
    'class' => 'hookline',
    'prefix' => '<span class="hideme">:</span> '
));
$workpackageNumber = $this->literal(array(
    'property' => 'fp:workpackageNumber'));

$abstract = $this->literal(array(
    'property' => 'dcterms:description',
    'tag' => 'p',
    'class' => 'abstract'
));

?>
<header class="intro">
    <h1><?php echo "WP ". $workpackageNumber. " &ndash; " . $this->title; /*. $hookline*/ ?></h1>
</header> <!-- /.intro -->
<?php
echo $abstract;

 echo $this->query(array(
        'where' => '?resourceUri fp:workpackage <'.$this->resourceUri.'>. ?resourceUri a fp:Task.',
        'template' => 'identifiertable',
        'prefix' => '<h1>Tasks</h1>'
    ));

//echo $this->literal(array('tag' => 'div', 'class' => 'abstract')); // uses default content properties
#echo $this->renderx(array('template' => 'local/items/publications.phtml'));

