 <?php

// prepare vars from the querylist helper
$resourceUri = $this->resourceUri;
$title       = $this->title;
$oddclass    = $this->oddclass;
$tag         = (isset($this->tag)) ? $this->tag : 'table';

$identifier  = $this->literal(array(
    'property' => 'dcterms:identifier'
));

if ( ($this->listhint == 'first') || ($this->rowcount == 1) ) {
    echo "<$tag>" . PHP_EOL;
}

// if we have a literal item, do not do anything but an li item
if (!Erfurt_Uri::check($resourceUri)) {
    echo "<tr class='$oddclass'>$title</tr>";
} else {
    $link = $this->link(array(
        'uri' => $resourceUri, 'text' => $title
    ));

    // try to prepare an active class
    if (isset($this->active)) {
        $activeResource = $this->active;
    } else {
        $activeResource = (string) OntoWiki::getInstance()->selectedResource;
    }
    if ($resourceUri == $activeResource) {
        $active = ' active';
    } else {
        $active = '';
    }
?>
    <tr class="<?php echo $oddclass . $active ?>" about="<?php echo $this->curie($resourceUri) ?>">
     <td><?php echo $identifier  ?></td>
    <td>
        <?php echo $link ?>
<?php
    if (isset($this->activeSuffix)) {
        if ($resourceUri == $activeResource) {
            echo $this->activeSuffix;
        }
    }
?>
   </td> </tr>
<?php
}

if ( ($this->listhint == 'last') || ($this->rowcount == 1) ) {
    echo "</$tag>" . PHP_EOL;
}
