<?php

// prepare vars from the querylist helper
$resourceUri = $this->resourceUri;
$title       = $this->title;
$oddclass    = $this->oddclass;
$tag         = (isset($this->tag)) ? $this->tag : 'ul';

if ( ($this->listhint == 'first') || ($this->rowcount == 1) ) {
    echo "<$tag>" . PHP_EOL;
}

// if we have a literal item, do not do anything but an li item
if (!Erfurt_Uri::check($resourceUri)) {
    echo "<span>$title</span>";
} else {
    $seeAlso  = $this->literal(array(
        'property' => 'rdfs:seeAlso', 
        'plain' => 'true'
    ));
    
    $link = $title;
    if($seeAlso != ""){
      $link = $this->link(array(
        'uri' => $seeAlso, 
        'text' => $title, 
        'direct' => true,
        'target' => '_blanc'
      ));
    }
    
    // try to prepare an active class
    if (isset($this->active)) {
        $activeResource = $this->active;
    } else {
        $activeResource = (string) OntoWiki::getInstance()->selectedResource;
    }
    if ($resourceUri == $activeResource) {
        $active = ' active';
    } else {
        $active = '';
    }
?>
    <li class="<?php echo  $oddclass.$active ?>" about="<?php echo $this->curie($resourceUri) ?>">
        <?php echo $link ?>
<?php
    if (isset($this->activeSuffix)) {
        if ($resourceUri == $activeResource) {
            echo $this->activeSuffix;
        }
    }
?>
    </li>
<?php
}

if ( ($this->listhint == 'last') || ($this->rowcount == 1) ) {
    echo "</$tag>" . PHP_EOL;
}
